name: Docker Image

on:
  schedule:
    - cron: '09 1 * * *'
  push:
    branches: [ main ]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Build docker image and push to Github
        uses: docker/build-push-action@v1
        with:
          username: welbymcroberts
          password: ${{ secrets.CR_PAT }}
          registry: ghcr.io
          repository: ${{ github.repository }}/rsyslog
          tag_with_sha: true
          tag_with_ref: true
          tags: latest
